language: java

jdk:
  - openjdk11

sudo: false
env:
  global:
    #key for github
    #GITHUB_OAUTH_TOKEN
    - secure: "FMYS4jYVhrsi38R/OF8aUV+wa7g+zuEKbkP7JNbNyBEfB0BcLjgok5g2RpNEabzufgWwoIbG3NB4jI78CIjhHzi65/7EzAVEUfm/GWSW1AJIj5E8FuHoSZ8ZsGXM7vHOQH0ed/AHZcxEr6Z1Vu4coZSJyM4WvgtenMxz1AsIjZomyZNofCKFOao5R60v4wOOblrTylhi1Tpm1E+b7y7/Q952E0CesqFEb5hwGWQyNYu/ROGqLYrGMDEiy9g2eSvhrS84zPvhzw0Yf02DyZ70JBtGKC1yKKsOw9kAzJI/aM0DI2keagYiXabq4qzgf0j5bDALsfT05F1g+8GNTkE0GMUkSKhGrrJZCiSaX8MQbedW7O0Zw+8sICprEmF0P/mSK6mjZs0dTdkvxFnxyTLeel4NMtEX4Xx4Qp/Qo6ou5ywb9o3BvCD8xhcd/BdyzgCV/0fd0M4ztZki5xhF3vo9/saopbIBVvwx4HF0R0z4vx1q2mhPSFUbSwEsQackeWXaKTrcg1zDS4AxC1zd4Pqv/e1+UuvAG2cyg8JS94TNQ3e9iDvzAhFY5DhTnu2Osdt0ZB2TgA2CjyCzAn8xq88J1gBASSp/fRo6Y5XobTI/U3Phzpc9sP0GeXP/gvub/fLyn/+bcrMRWjWJBsdUITaYaTvaTWzP3UIY12bKieo9aR8="
    #SONAR_TOKEN
    - secure: "gk3GivGaFfW+FMzAauXsz4TgggHEtjyQ08RK6/tGBLgb41lMGmWrPw25SbS/SLkP2P/2424PRDyRea4umLmuJbrdwD5rBT3gNBJfleg3F0BSem/eqxIOCTpEyu4YJ0Vd0u69SSs7N0xfVUJ8o1qW9pXgSCMtGuTokk5nOmDuJ4gCy9KCjpC00IaR+2M/nOZ1KrBcC+fJxouKrFdvB5n91ZvgKhbsvJqks42YMpRsncMboseoz8817owu/3Jd2z+d/oXKIdgjmv6fqBI4vfJINPWofJ7u7dFnt+VWolIDCdXG4HmfHmAnRw7+DgAR3X8P+2GraVKdcnuwK7lvoptJ7eehdpJRH0FCRxygMHxvmxa3fy6SqK/JJm2xTjMdZqgtDxKBS5Tilk6IS45ByrYkqzbjZ363KjDFrBJCpqbbomora3ltVnQbAYtzONDoQdBSnQKG4YPtVw9oIG7rAXerO/ZQHhjm7ch7yHLfsBMAt7mKwprrdJiF+KVCnSY+yi9aTZxV9ehbcwYZEVsN2G8Dg8XhXAo3Zp2rt3nn7jRowdqB2UjYzzEZzyRi35M7csjJ8FWlnATMNMWizfZHikuoG7rD6P1T26a7YstRoLxKKbrnZZo7ifV2SDWcGwzuJ3nWXxn64y+avBxnFNTC0g73q7mWGc5QmntBdKb1wFecXRk="
branches:
  only:
    - main
    - exercises

addons:
  sonarcloud:
    organization: "albertoirurueta-github"

script:
  - mvn clean jacoco:prepare-agent verify jacoco:report
  - mvn site -DskipTests

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: exercises
