language: java

jdk:
  - openjdk11

sudo: false
env:
  global:
    #key for github
    #GITHUB_OAUTH_TOKEN
    - secure: "CG8N1C88T7+Xa08X7ImHGLIv6C2d9sLw4SFZv+Lf0AFQMoKRl4f3JZqwjFb5r0tH6G1A8vw+NtmfMZSVgpWs7LMOWD82ujOUpsxb4yYX9UFRkUBMI6IbsC3I+wh4d23yaEQclTzotV73mSiNRuyvsSLtXwbvYY8TEnKrx5yd5i2+/ueXgo4tvIDk4orKtASOfYuB50NkHKmeZTE1uCi1zNVczdym7QIqfqxYCFVYZ/agsJuNE3YVZbXTeax1Z0c11Z4q4upamlM6v230yIx6mtl9xhfQx83+fb8Yb7+jz7eEx4AfhC37hVfmtzXvj6y/b3NA7Y9XDmIiRsNCDgn9lZx3epfl53X/trzwpMdBt91YlRyrg2CoqgYTxZgePSYyUowNFfSYk4RhXXZUF5+4gPEa5H6boZJkjYMPifav5pkQioqJ9gn67xP/tJiO9Vy/61PKCM6ptcZz0Nu9i1OwTAIDs50rLLkooJKxoTWVGoQfPlvUqrqba9JJ0stX2dhOGoXg2IKAx83oxnQ/e5fhGRpbNMS53Tby5zIt2W9tEZFzeV95yxgyXh1XSV2AsaVT/5/k0USGFF4FHspfD371hAquu41J5n+DTpUzBA0mXaDhBc1zyutGelrOBKrKbjhy1tWl/QcwcRNwHQPWNJ2R5fGFD9gGsJxHUDV3Z4DJ1go="
    #SONAR_TOKEN
    #- secure: "dLbvQADzAZR4W1TIXGXeLwZDNGftUWEDvStoYoiRa/S7uHADXOmL72lD3HqEWVOjVAO0mBrNbsLqonFLDyc3wI9qj4Z7Fz3kB63b2EpSVZLtao1YLgD8Uo9sUDLrNSxMNDh2IcBF/r/qbU0Uv1WTIAKDODKa2TZTSti+X8vTdgvoJ7L89VKTvDnSHMroObd6BjMsuIcEsrv4sCRUpKyiQXjpaIWS5v8lf17ZmNwIGXb0QEpqYz0wyBNXCHXcv7p6gIAW+kxg1hjLkIWAnTWOcELSSGWQS4pxGIiju4NGrHVyTRGg+ZFvkjreXIWqTsJMaiKruxkmwRTiLJyaksCUujyVmfLBIkVH+CdApmeIrMBRbOR4xiMo5cEOdxFJ8TZAbjiUD4hkewZvq1rQNQdriD71SA4uJAuHWs1JU2+j99UDuRusR6rslWQGJtDy1+1FwyG1QksJi8OiiAX9+Kja2IxOtDIaP/ER1pjzvWQj1VZk7YEdXZQdJAO2UprK6YwVzyOL6lCmhWLD2L588n95NgwZCYirT2qQ7k6q/egtgNi365YrMDR7MYSNltWyEqOZWuTrtbVk2knIOE+9lMWZL+ewqU+R/A2aUB2TP07j6F7ZaKUBkm3ohKCtgYeMbau6taq9UXgF4q7hdtFrMd9muDuf9HuCjiF3YybZNpTDD7Q="
branches:
  only:
    - main
    - exercises

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "bC+zFBgd88EYtDVm3NYZBmzy5sEW7MRef32YSOSCBoxLm9O/2Zb75dI8PP9hfHjtiAP7LIUxvB1O6pC799tLZWxGPExj/mD9W0JNCl1dafoZ6dzEmk4O1cfwMCt2S+/TVFeY/P5yDFWiJJfz1TWag8q3kG2Y0o2p7Q97ZeHRLvuIqFVAaVKddvFkal9IfeUeXWzHAVfxc/U8RkQuc4lgSp0wE7Lu+8GnxlUcD7fh5XW9hl7y/G+Ei4QuQopieGz0qWgkVWZbnXU4iDtoSG4hA9OXmim7vhsiEGXohWwZ7+dTHrVRqRrNCP0mnK9F1g6v9FpWw9YkxBZSSttm2TRBp7jbu6Ay8heNuzbpx7bCCRBbI0veCTMRQ1Jc4cqooiCil1zPaK32vClA3i+aa3z/uO5CC1UXEKoapUUmJkZknBgQTiLoL+Q8gkZSWKCqb9N4wseHuInQdfixAE5Zz4NEHIhHMLmiUaZrtu7lwMoHtMDzDXcZCg0eUyoax1t6MH8D137/9cBJ1aPMtLVgBoG10GrAnYnaXQqj3pLo1U76dmN97vu1hbNdVRLjYJpd0de61lfqe6z89HXkPf1I5L7wF/yEOWUNOmB+ljcYOY2QyhNumRD07HlWxbrCCgMVSX6hji0XV7c9StxbCyL5uc6V7+1HL4kdwt6oDMZFWEPAyq8="    

script:
  - mvn clean jacoco:prepare-agent verify jacoco:report
  - mvn site -DskipTests
  - sonar-scanner
  #- mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: exercises
