language: java

jdk:
  - openjdk11

sudo: false

branches:
  only:
    - main
    - exercises

script:
  - mvn clean jacoco:prepare-agent verify jacoco:report
  - mvn site -DskipTests
  - mvn sonar:sonar

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: exercises
